=== Cesar7s/ordinario-ftw/Proyecto/xml/dinosaurio.dtd
<!ELEMENT dinopedia (dinosaurio*)>
<!ELEMENT dinosaurio (nombre, descripcion, genero, tipo, opcionales?)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>

<!ELEMENT opcionales (nombre_cientifico?, fecha_descubrimiento?, descubridor?, periodo_vida?)>
<!ELEMENT nombre_cientifico (#PCDATA)>
<!ELEMENT fecha_descubrimiento (#PCDATA)>
<!ELEMENT descubridor (#PCDATA)>
<!ELEMENT periodo_vida (#PCDATA)>

=== Cesar7s/ordinario-ftw/Proyecto/xml/dinosaurio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dinopedia SYSTEM "dinosaurio.dtd">

<dinopedia>
    <dinosaurio>
        <nombre>T-Rex</nombre>
        <descripcion>Dinosaurio carnívoro del periodo Cretácico.</descripcion>
        <genero>Theropoda</genero>
        <tipo>Carnívoro</tipo>
        <opcionales>
            <nombre_cientifico>Tyrannosaurus rex</nombre_cientifico>
            <fecha_descubrimiento>1905</fecha_descubrimiento>
            <descubridor>Barnum Brown</descubridor>
            <periodo_vida>Cretácico superior</periodo_vida>
        </opcionales>
    </dinosaurio>
</dinopedia>
